# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   timeout: 5000
#   username: deploy
#   password: deploy
#   socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: online_blogs_development

staging:
  <<: *default

production:
  adapter: mysql2
  pool: 25
  encoding: utf8
  database: online_blogs_development
  # host: 127.0.0.1
  username: deploy
  password: deploy

test:
  <<: *default
  database: online_blogs_test

