default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: nandudu
  host: localhost
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: online_blogs_development

staging:
  <<: *default

production:
  adapter: mysql2
  pool: 5
  encoding: utf8
  reconnect: false
  database: online_blogs_production
  host: localhost
  # host: 127.0.0.1
  username: root
  password: nandudu

test:
  <<: *default
  database: online_blogs_test

