default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: 

development:
  <<: *default
  database: online_blogs_development

staging:
  <<: *default

production:
  adapter: mysql2
  pool: 25
  encoding: utf8
  database: online_blogs_development
  # host: localhost
  username: root
  password: 

test:
  <<: *default
  database: online_blogs_test

