default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: 

development:
  <<: *default
  database: online_blogs_development

staging:
  <<: *default

production:
  <<: *default
  database: online_blogs_production

test:
  <<: *default
  database: online_blogs_test

remote:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3
