# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a1eb0050fdba1b003d2b58cb9b3391af02f590e470360465aef2f4eebfe64fcaa68228cee154193d6e4be8d7e5cd6d54568d15efae2ef3d6082c1591372299

test:
  secret_key_base: 370d4c3693ba0fc01e30b4e78c8d2f801bda2e2db694750036cb97c979dd23eabfac59bfa9e57bb5774bcb6a33d14cd0748837ae3389bf6164c23bc15770ec7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
